/**
 * TelegramAdapter: Inbound adapter implementing TelegramServicePort
 * Follows hexagonal architecture pattern for MidasTS
 * 
 * This is a simplified version that only implements core functionality
 * required by the TelegramServicePort interface
 */
import { Telegraf, Scenes, session, Context } from 'telegraf';
import { logger } from '../../utils/logging';
import { TelegramServicePort } from '../../ports/inbound/telegram-service-port';

// Interfaces
interface BotSession {
  authenticated: boolean;
  userId: number;
  username: string;
  notifications: {
    signals: boolean;
    trades: boolean;
    portfolioUpdates: boolean;
  };
}

// Define context type extending Telegraf's Context
interface BotContext extends Context {
  session: BotSession;
}

// Interface for service dependencies
interface TelegramAdapterDependencies {
  binanceService: any;
  deepSeekService: any;
  lunarCrushService: any;
  marketDataService: any;
  tradeHistoryService: any;
  dbService: any;
}

/**
 * Telegram adapter implementing TelegramServicePort
 * Acts as an inbound adapter in the hexagonal architecture
 */
export class TelegramAdapter implements TelegramServicePort {
  private bot: Telegraf<BotContext>;
  private _isRunning: boolean = false;
  private authorizedUsers: number[] = [];
  private dependencies: TelegramAdapterDependencies;
  
  constructor(dependencies: TelegramAdapterDependencies) {
    this.dependencies = dependencies;
    
    // Get token from .env and provide a default value if it doesn't exist
    const token = process.env.TELEGRAM_BOT_TOKEN || '';
    
    if (!token) {
      logger.error('TELEGRAM_BOT_TOKEN not configured in .env');
      throw new Error('Telegram token not configured');
    }
    
    // Initialize the bot
    this.bot = new Telegraf<BotContext>(token);
    
    // Set up authorized users
    this.authorizedUsers = process.env.TELEGRAM_AUTHORIZED_USERS ? 
      process.env.TELEGRAM_AUTHORIZED_USERS.split(',').map((id: string) => parseInt(id.trim())) : [];
    
    // Basic middleware
    this.setupMiddleware();
    
    logger.info('Telegram adapter initialized');
  }
  
  /**
   * Start the Telegram bot and connect to the Telegram API
   */
  public async start(): Promise<void> {
    if (this._isRunning) {
      logger.warn('Telegram bot is already running');
      return;
    }
    
    try {
      await this.bot.launch();
      this._isRunning = true;
      
      // Set up basic commands
      this.bot.command('start', ctx => ctx.reply('Welcome to MidasTS Bot!'));
      this.bot.command('help', ctx => ctx.reply('This is a simplified version of the MidasTS Bot'));
      
      logger.info('Telegram bot started successfully');
      
      // Set up signal handling for graceful shutdown
      process.once('SIGINT', () => this.stop('SIGINT'));
      process.once('SIGTERM', () => this.stop('SIGTERM'));
    } catch (error) {
      logger.error({ error }, 'Error starting Telegram bot');
      throw error;
    }
  }
  
  /**
   * Stop the bot
   */
  public async stop(reason: string = 'manual'): Promise<void> {
    if (!this._isRunning) {
      logger.warn('Telegram bot is not running');
      return;
    }
    
    try {
      await this.bot.stop(reason);
      this._isRunning = false;
      logger.info({ reason }, 'Telegram bot stopped');
    } catch (error) {
      logger.error({ error, reason }, 'Error stopping Telegram bot');
    }
  }
  
  /**
   * Send a notification to all authorized users
   */
  public async sendNotificationToAll(message: string): Promise<void> {
    for (const userId of this.authorizedUsers) {
      try {
        await this.bot.telegram.sendMessage(userId, message, { parse_mode: 'HTML' });
      } catch (error) {
        logger.error({ error, userId }, 'Error sending notification');
      }
    }
  }
  
  /**
   * Send a trading signal alert to users with signal notifications enabled
   */
  public async sendTradingSignal(symbol: string, signal: any): Promise<void> {
    // Build formatted message
    const message = `
<b>🔔 New Trading Signal</b>

<b>Symbol:</b> ${symbol}
<b>Action:</b> ${signal.action}
<b>Confidence:</b> ${(signal.confidence * 100).toFixed(1)}%
${signal.entry ? `<b>Entry:</b> $${signal.entry}` : ''}
${signal.stopLoss ? `<b>Stop Loss:</b> $${signal.stopLoss}` : ''}
${signal.takeProfit ? `<b>Take Profit:</b> $${signal.takeProfit}` : ''}
${signal.reasoning ? `\n<b>Analysis:</b> ${signal.reasoning}` : ''}

<i>Generated by DeepSeek Reasoner at ${new Date().toLocaleTimeString()}</i>
    `;
    
    // Send to all authorized users
    await this.sendNotificationToAll(message);
  }
  
  /**
   * Send order execution notification
   */
  public async sendOrderNotification(order: any): Promise<void> {
    // Build order execution message
    const message = `
<b>✅ Order Executed</b>

<b>Type:</b> ${order.side === 'BUY' ? '🟢 Buy' : '🔴 Sell'}
<b>Symbol:</b> ${order.symbol}
<b>Price:</b> $${parseFloat(order.price).toFixed(4)}
<b>Quantity:</b> ${parseFloat(order.quantity).toFixed(6)}
<b>Total:</b> $${(parseFloat(order.price) * parseFloat(order.quantity)).toFixed(2)}

<i>Executed on Binance at ${new Date().toLocaleTimeString()}</i>
    `;
    
    await this.sendNotificationToAll(message);
  }
  
  /**
   * Check if the bot is currently running
   */
  public isRunning(): boolean {
    return this._isRunning;
  }
  
  /**
   * Configure the bot middleware
   */
  private setupMiddleware(): void {
    // Session middleware to maintain state
    this.bot.use(session());
    
    // Authentication middleware
    this.bot.use(async (ctx, next) => {
      // Initialize session if it doesn't exist
      if (!ctx.session) {
        ctx.session = {
          authenticated: false,
          userId: ctx.from?.id || 0,
          username: ctx.from?.username || 'unknown',
          notifications: {
            signals: true,
            trades: true,
            portfolioUpdates: false
          }
        };
      }
      
      // Check if the user is authorized
      const userId = ctx.from?.id;
      if (userId && this.authorizedUsers.includes(userId)) {
        ctx.session.authenticated = true;
        return next();
      }
      
      // If not authorized, only allow /start command
      if (ctx.message && 'text' in ctx.message && ctx.message.text === '/start') {
        return next();
      }
      
      // Reject access for unauthorized users
      await ctx.reply('⛔ You are not authorized to use this bot.');
    });
  }
}
